# -*- coding: utf-8 -*-
# @Time : 2020/2/11
# @Author : zhang
# @Site :
# @File : config.py
# @Software: PyCharm

from NewApp.settings import SQLALCHEMY_DATABASE_URI, SQLALCHEMY_MAX_OVERFLOW, SQLALCHEMY_POOL_RECYCLE, \
    SQLALCHEMY_POOL_SIZE, SQLALCHEMY_POOL_TIMEOUT


class Config(object):
    SQLALCHEMY_DATABASE_URI = SQLALCHEMY_DATABASE_URI
    SQLALCHEMY_TRACK_MODIFICATIONS = False
    SQLALCHEMY_POOL_SIZE = SQLALCHEMY_POOL_SIZE
    SQLALCHEMY_POOL_TIMEOUT = SQLALCHEMY_POOL_TIMEOUT
    SQLALCHEMY_POOL_RECYCLE = SQLALCHEMY_POOL_RECYCLE
    SQLALCHEMY_MAX_OVERFLOW = SQLALCHEMY_MAX_OVERFLOW